language: c
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq gcc-avr binutils-avr avr-libc
script:
  - cd Utility
  - echo Building utilities
  - cd string_parser
  - make
  - cd ../pindef_parser
  - make
  - cd ../../Code
  - make string
  - make pin
  - make