#!/bin/bash

if [ $# -ne 1 ]; then
    echo $0: Error. Usage : absolute_path_depend fileName
    exit 1
fi

name=$1

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
OLD_PATTERN=src
NEW_PATTERN=$DIR\/src
sed -i  "s@$OLD_PATTERN@$NEW_PATTERN@g" $name
NEW_PATTERN=$DIR\/obj\/
echo -n $DIR/obj/ | cat - $name > temp && mv temp $name
