#!/bin/bash
# This script check if the microcontroller is detected and retrieve fuse option into two file
avrdude -p m32u4 -U lfuse:r:low_fuse_val.hex:h -U hfuse:r:high_fuse_val.hex:h -cstk500v1 -PCOM3 -b19200
