
# Makefile for Password Wallet - Test Version
# All rights reserved - Thomas Chevalier - 2016

CC=avr-gcc
DEVICE=atmega32u4
CFLAGS= -Os -Wall -DF_CPU=12000000UL -mmcu=$(DEVICE) -std=gnu99 -fshort-enums -ffunction-sections -fdata-sections -MMD
LDFLAGS= -mmcu=$(DEVICE)
BDIR=build
SDIR=src
DDIR=.
ODIR=.
SRC=$(wildcard $(SDIR)/*.c)
_OBJS=$(subst $(SDIR)/,$(ODIR)/,$(SRC))
OBJS=$(_OBJS:.c=.o)
DEPEND=$(OBJS:.o=.d)

all : main

main: $(OBJS)
	$(CC) -o $(BDIR)/$@ $^ $(LDFLAGS)
	avr-objcopy -O ihex -R .eeprom $(BDIR)/main $(BDIR)/main.hex
	avr-size -C --mcu=$(DEVICE) $(BDIR)/main

# Include dependencies files, auto generated by -MM command of the compiler (http://scottmcpeak.com/autodepend/autodepend.html)
-include $(DEPEND)

$(ODIR)/%.o: $(SDIR)/%.c
	$(CC) $(CFLAGS) -o $(ODIR)/$*.o -c $(SDIR)/$*.c
	@$(CC) -MM $(CFLAGS) $(SDIR)/$*.c > $*.d
	@mv -f $*.d $*.d.tmp
	@sed -e 's|.*:|$(ODIR)/$*.o:|' < $*.d.tmp > $*.d
	@sed -e 's/.*://' -e 's/\\$$//' < $*.d.tmp | fmt -1 | \
	  sed -e 's/^ *//' -e 's/$$/:/' >> $*.d
	@rm -f $*.d.tmp
	
.PHONY: clean clean-all rebuild

clean:
	@rm -f $(DEPEND)
	@rm -f $(OBJS)

clean-all: clean
	@rm -rf $(BDIR)/main $(BDIR)/main.hex

rebuild: clean-all main
	
