
# Makefile for Password Wallet - Test Version
# All rights reserved - Thomas Chevalier - 2016

CC=avr-gcc -Os -flto -s
DEVICE=atmega32u4
CFLAGS= -Wall -DF_CPU=16000000UL -mmcu=$(DEVICE) -std=gnu99 -fshort-enums -ffunction-sections -fdata-sections
LDFLAGS= -mmcu=$(DEVICE) -Wl,--gc-sections
BDIR=build
SDIR=src
DDIR=depend
ODIR=obj
SRC=$(wildcard $(SDIR)/*.c)
_OBJS=$(subst $(SDIR)/,$(ODIR)/,$(SRC))
OBJS=$(_OBJS:.c=.o)
_DEPEND=$(OBJS:.o=.d)
DEPEND=$(subst $(ODIR), $(DDIR), $(_DEPEND))

all: main

main: $(OBJS)
	@$(CC) -o $(BDIR)/$@ $^ $(LDFLAGS)
	@avr-objcopy -O ihex -R .eeprom $(BDIR)/main $(BDIR)/main.hex
	@avr-size -C --mcu=$(DEVICE) $(BDIR)/main

# Include dependencies files, auto generated by -MM command of the compiler (http://scottmcpeak.com/autodepend/autodepend.html)
-include $(DEPEND)

$(ODIR)/%.o: $(SDIR)/%.c
	@printf "Compiling %-23s to %s\n" "$(SDIR)/$*.c" "$(ODIR)/$*.o"
	@$(CC) $(CFLAGS) -o $(ODIR)/$*.o -c $(SDIR)/$*.c
	@$(CC) -MM $(CFLAGS) $(SDIR)/$*.c > $*.d
	@./absolute_path_depend $*.d
	@mv $*.d $(DDIR)/$*.d
#@(echo -n "../$(ODIR)/"&cat $(DDIR)/$*.d)> $(DDIR)/$*.d.tmp
#@mv $(DDIR)/$*.d.tmp $(DDIR)/$*.d
	
.PHONY: clean clean-all rebuild

clean:
	@rm -f $(DEPEND)
	@rm -f $(OBJS)

clean-all: clean
	@rm -rf $(BDIR)/main $(BDIR)/main.hex

rebuild: clean-all main
	
