#!/bin/bash

avr-gcc -Os -Wall -DF_CPU=8000000UL -mmcu=atmega32u4 -std=gnu99 -fshort-enums -ffunction-sections -fdata-sections -MMD  -c -o blink.o blink.c 

avr-gcc -mmcu=atmega32u4 blink.o -o main

avr-objcopy -O ihex -R .eeprom main main.hex
avr-size -C --mcu=atmega32u4 main
