/*
 * File auto-generated by string_parser.
 * Copyright - Thomas Chevalier - 2017.
 * thomasom.chevalier@gmail.com
 * File created on 12-08-2017 15-14-50
*/

#ifndef STRING_HEADER_THOMAS_CHEVALIER
#define STRING_HEADER_THOMAS_CHEVALIER

#include <avr/pgmspace.h>

#define str_change_key_what_index (0)
#define str_change_key_what_len (17)
#define str_change_key_update_pwd_index (18)
#define str_change_key_update_pwd_len (24)
#define str_change_key_here_index (43)
#define str_change_key_here_len (16)
#define str_comm_what_index (60)
#define str_comm_what_len (18)
#define str_comm_no_unplug_index (79)
#define str_comm_no_unplug_len (17)
#define str_error_card_index (97)
#define str_error_card_len (23)
#define str_error_auth_index (121)
#define str_error_auth_len (25)
#define str_error_read_index (147)
#define str_error_read_len (17)
#define str_error_pwd_index (165)
#define str_error_pwd_len (20)
#define str_error_not_enough_mem_index (186)
#define str_error_not_enough_mem_len (20)
#define str_error_cannot_add_index (207)
#define str_error_cannot_add_len (16)
#define str_option_pwd_index (224)
#define str_option_pwd_len (16)
#define str_option_sort_index (241)
#define str_option_sort_len (7)
#define str_option_param_index (249)
#define str_option_param_len (14)
#define str_option_add_index (264)
#define str_option_add_len (20)
#define str_option_change_pwd_index (285)
#define str_option_change_pwd_len (20)
#define str_option_change_usr_index (306)
#define str_option_change_usr_len (19)
#define str_option_change_name_index (326)
#define str_option_change_name_len (11)
#define str_option_regen_index (338)
#define str_option_regen_len (9)
#define str_option_delete_index (348)
#define str_option_delete_len (9)
#define str_option_sort_no_index (358)
#define str_option_sort_no_len (10)
#define str_option_sort_use_index (369)
#define str_option_sort_use_len (15)
#define str_option_sort_alpha_index (385)
#define str_option_sort_alpha_len (7)
#define str_option_change_key_index (393)
#define str_option_change_key_len (19)
#define str_option_show_key_index (413)
#define str_option_show_key_len (20)
#define str_option_orientation_index (434)
#define str_option_orientation_len (21)
#define str_option_keyboard_layout_index (456)
#define str_option_keyboard_layout_len (22)
#define str_option_self_test_index (479)
#define str_option_self_test_len (10)
#define str_option_full_reset_index (490)
#define str_option_full_reset_len (8)
#define str_order_approach_index (499)
#define str_order_approach_len (21)
#define str_order_type_pwd_name_index (521)
#define str_order_type_pwd_name_len (20)
#define str_order_type_pwd_data_index (542)
#define str_order_type_pwd_data_len (22)
#define str_order_type_usr_name_index (565)
#define str_order_type_usr_name_len (27)
#define str_recovery_eraseMem_index (593)
#define str_recovery_eraseMem_len (17)
#define str_recovery_title_index (611)
#define str_recovery_title_len (20)
#define str_recovery_full_index (632)
#define str_recovery_full_len (17)
#define str_recovery_key_index (650)
#define str_recovery_key_len (14)
#define str_reset_external_index (665)
#define str_reset_external_len (13)
#define str_reset_brownout_index (679)
#define str_reset_brownout_len (19)
#define str_reset_watchdog_index (699)
#define str_reset_watchdog_len (14)
#define str_reset_jtag_index (714)
#define str_reset_jtag_len (10)
#define str_reset_usb_index (725)
#define str_reset_usb_len (9)
#define str_self_test_fram_fail_index (735)
#define str_self_test_fram_fail_len (19)
#define str_self_test_rfid_fail_index (755)
#define str_self_test_rfid_fail_len (22)
#define str_self_test_button_fail_index (778)
#define str_self_test_button_fail_len (20)
#define str_self_test_good_index (799)
#define str_self_test_good_len (20)
#define str_self_test_fail_index (820)
#define str_self_test_fail_len (19)

static const uint8_t stringData[840] PROGMEM =
{
'M', '.', 'a', '.', 'j', '.', ' ', 'd', 'e', ' ', 'l', 'a', ' ', 'c', 'l', 'e', 
'f', '\0', 'M', '.', 'a', '.', 'j', '.', ' ', 'd', 'e', 's', ' ', 'm', 'o', 't', 
's', ' ', 'd', 'e', ' ', 'p', 'a', 's', 's', 'e', '\0', 'V', 'o', 'i', 'c', 'i', 
' ', 'v', 'o', 't', 'r', 'e', ' ', 'c', 'l', 'e', 'f', '\0', 'T', 'r', 'a', 'n', 
's', 'f', 'e', 'r', 't', ' ', 'e', 'n', ' ', 'c', 'o', 'u', 'r', 's', '\0', 'N', 
'E', ' ', 'P', 'A', 'S', ' ', 'D', 'E', 'B', 'R', 'A', 'N', 'C', 'H', 'E', 'R', 
'\0', 'E', 'R', 'R', 'E', 'U', 'R', ' ', ':', ' ', 'c', 'a', 'r', 't', 'e', ' ', 
'i', 'n', 'c', 'o', 'n', 'n', 'u', 'e', '\0', 'E', 'R', 'R', 'E', 'U', 'R', ' ', 
'd', '\'', 'a', 'u', 't', 'h', 'e', 'n', 't', 'i', 'f', 'i', 'c', 'a', 't', 'i', 
'o', 'n', '\0', 'E', 'r', 'r', 'e', 'u', 'r', ' ', 'd', 'e', ' ', 'l', 'e', 'c', 
't', 'u', 'r', 'e', '\0', 'M', 'a', 'u', 'v', 'a', 'i', 's', ' ', 'm', 'o', 't', 
' ', 'd', 'e', ' ', 'p', 'a', 's', 's', 'e', '\0', 'M', 'e', 'm', 'o', 'i', 'r', 
'e', ' ', 'i', 'n', 's', 'u', 'f', 'f', 'i', 's', 'a', 'n', 't', 'e', '\0', 'A', 
'j', 'o', 'u', 't', ' ', 'i', 'm', 'p', 'o', 's', 's', 'i', 'b', 'l', 'e', '\0', 
'M', 'o', 't', ' ', 'd', 'e', ' ', 'p', 'a', 's', 's', 'e', ' ', '.', '.', '.', 
'\0', 'T', 'r', 'i', ' ', '.', '.', '.', '\0', 'P', 'a', 'r', 'a', 'm', 'e', 't', 
'r', 'e', 's', ' ', '.', '.', '.', '\0', 'N', 'o', 'u', 'v', 'e', 'a', 'u', ' ', 
'm', 'o', 't', ' ', 'd', 'e', ' ', 'p', 'a', 's', 's', 'e', '\0', 'C', 'h', 'a', 
'n', 'g', 'e', 'r', ' ', 'm', 'o', 't', ' ', 'd', 'e', ' ', 'p', 'a', 's', 's', 
'e', '\0', 'C', 'h', 'a', 'n', 'g', 'e', 'r', ' ', 'i', 'd', 'e', 'n', 't', 'i', 
'f', 'i', 'a', 'n', 't', '\0', 'C', 'h', 'a', 'n', 'g', 'e', 'r', ' ', 'n', 'o', 
'm', '\0', 'R', 'e', 'g', 'e', 'n', 'e', 'r', 'e', 'r', '\0', 'S', 'u', 'p', 'p', 
'r', 'i', 'm', 'e', 'r', '\0', 'P', 'a', 's', ' ', 'd', 'e', ' ', 't', 'r', 'i', 
'\0', 'P', 'a', 'r', ' ', 'u', 't', 'i', 'l', 'i', 's', 'a', 't', 'i', 'o', 'n', 
'\0', 'P', 'a', 'r', ' ', 'n', 'o', 'm', '\0', 'C', 'h', 'a', 'n', 'g', 'e', 'r', 
' ', 'c', 'l', 'e', 'f', ' ', 'm', 'a', 'i', 't', 'r', 'e', '\0', 'A', 'f', 'f', 
'i', 'c', 'h', 'e', 'r', ' ', 'c', 'l', 'e', 'f', ' ', 'm', 'a', 'i', 't', 'r', 
'e', '\0', 'R', 'e', 't', 'o', 'u', 'r', 'n', 'e', 'r', ' ', 'l', '\'', 'a', 'f', 
'f', 'i', 'c', 'h', 'a', 'g', 'e', '\0', 'C', 'h', 'a', 'n', 'g', 'e', 'r', ' ', 
'l', 'a', 'n', 'g', 'u', 'e', ' ', 'c', 'l', 'a', 'v', 'i', 'e', 'r', '\0', 'D', 
'i', 'a', 'g', 'n', 'o', 's', 't', 'i', 'c', '\0', 'F', 'O', 'R', 'M', 'A', 'T', 
'E', 'R', '\0', 'A', 'p', 'p', 'r', 'o', 'c', 'h', 'e', 'z', ' ', 'v', 'o', 't', 
'r', 'e', ' ', 'c', 'a', 'r', 't', 'e', '\0', 'E', 'n', 't', 'r', 'e', 'z', ' ', 
'l', 'e', ' ', 'n', 'o', 'm', ' ', 'd', 'u', ' ', 'm', 'd', 'p', '\0', 'E', 'n', 
't', 'r', 'e', 'z', ' ', 'l', 'e', ' ', 'm', 'o', 't', ' ', 'd', 'e', ' ', 'p', 
'a', 's', 's', 'e', '\0', 'E', 'n', 't', 'r', 'e', 'z', ' ', 'l', 'e', ' ', 'n', 
'o', 'm', ' ', 'd', '\'', 'u', 't', 'i', 'l', 'i', 's', 'a', 't', 'e', 'u', 'r', 
'\0', 'F', 'o', 'r', 'm', 'a', 't', 'a', 'g', 'e', ' ', 'm', 'e', 'm', 'o', 'i', 
'r', 'e', '\0', 'M', 'O', 'D', 'E', ' ', 'D', 'E', ' ', 'R', 'E', 'C', 'U', 'P', 
'E', 'R', 'A', 'T', 'I', 'O', 'N', '\0', 'F', 'O', 'R', 'M', 'A', 'T', 'A', 'G', 
'E', ' ', 'C', 'O', 'M', 'P', 'L', 'E', 'T', '\0', 'E', 'N', 'T', 'R', 'E', 'R', 
' ', 'L', 'A', ' ', 'C', 'L', 'E', 'F', '\0', 'R', 'e', 's', 'e', 't', ' ', 'e', 
'x', 't', 'e', 'r', 'n', 'e', '\0', 'R', 'e', 's', 'e', 't', ' ', 'b', 'a', 's', 
's', 'e', ' ', 't', 'e', 'n', 's', 'i', 'o', 'n', '\0', 'R', 'e', 's', 'e', 't', 
' ', 'w', 'a', 't', 'c', 'h', 'd', 'o', 'g', '\0', 'R', 'e', 's', 'e', 't', ' ', 
'J', 'T', 'A', 'G', '\0', 'R', 'e', 's', 'e', 't', ' ', 'U', 'S', 'B', '\0', 'M', 
'e', 'm', 'o', 'i', 'r', 'e', ' ', 'd', 'e', 'f', 'e', 'c', 't', 'u', 'e', 'u', 
's', 'e', '\0', 'M', 'o', 'd', 'u', 'l', 'e', ' ', 'r', 'f', 'i', 'd', ' ', 'd', 
'e', 'f', 'e', 'c', 't', 'u', 'e', 'u', 'x', '\0', 'B', 'o', 'u', 't', 'o', 'n', 
' ', 'd', 'e', 'f', 'e', 'c', 't', 'u', 'e', 'u', 'x', ' ', ':', ' ', '\0', 'A', 
'p', 'p', 'a', 'r', 'e', 'i', 'l', ' ', 'e', 'n', ' ', 'b', 'o', 'n', ' ', 'e', 
't', 'a', 't', '\0', 'A', 'p', 'p', 'a', 'r', 'e', 'i', 'l', ' ', 'd', 'e', 'f', 
'e', 'c', 't', 'u', 'e', 'u', 'x', '\0', };

#endif // STRING_HEADER_THOMAS_CHEVALIER
