/*
 * File auto-generated by string_parser.
 * Copyright - Thomas Chevalier - 2017.
 * thomasom.chevalier@gmail.com
 * File created on 18-09-2019 13-51-36
*/

#ifndef STRING_HEADER_THOMAS_CHEVALIER
#define STRING_HEADER_THOMAS_CHEVALIER

#include <avr/pgmspace.h>

#define str_backup_what_index (0)
#define str_backup_what_len (22)
#define str_backup_what_pixLen (124)
#define str_backup_what_centerX (2)
#define str_change_key_what_index (23)
#define str_change_key_what_len (17)
#define str_change_key_what_pixLen (79)
#define str_change_key_what_centerX (24)
#define str_change_key_update_pwd_index (41)
#define str_change_key_update_pwd_len (24)
#define str_change_key_update_pwd_pixLen (122)
#define str_change_key_update_pwd_centerX (3)
#define str_change_key_update_validation_index (66)
#define str_change_key_update_validation_len (23)
#define str_change_key_update_validation_pixLen (111)
#define str_change_key_update_validation_centerX (8)
#define str_change_key_update_card_index (90)
#define str_change_key_update_card_len (18)
#define str_change_key_update_card_pixLen (87)
#define str_change_key_update_card_centerX (20)
#define str_change_key_here_index (109)
#define str_change_key_here_len (16)
#define str_change_key_here_pixLen (84)
#define str_change_key_here_centerX (22)
#define str_comm_no_unplug_index (126)
#define str_comm_no_unplug_len (17)
#define str_comm_no_unplug_pixLen (96)
#define str_comm_no_unplug_centerX (16)
#define str_comm_yes_index (144)
#define str_comm_yes_len (3)
#define str_comm_yes_pixLen (18)
#define str_comm_yes_centerX (55)
#define str_comm_no_index (148)
#define str_comm_no_len (3)
#define str_comm_no_pixLen (18)
#define str_comm_no_centerX (55)
#define str_comm_enable_com_index (152)
#define str_comm_enable_com_len (14)
#define str_comm_enable_com_pixLen (76)
#define str_comm_enable_com_centerX (26)
#define str_error_card_index (167)
#define str_error_card_len (21)
#define str_error_card_pixLen (118)
#define str_error_card_centerX (5)
#define str_error_auth_index (189)
#define str_error_auth_len (23)
#define str_error_auth_pixLen (129)
#define str_error_auth_centerX (0)
#define str_error_read_index (213)
#define str_error_read_len (17)
#define str_error_read_pixLen (94)
#define str_error_read_centerX (17)
#define str_error_write_index (231)
#define str_error_write_len (17)
#define str_error_write_pixLen (93)
#define str_error_write_centerX (17)
#define str_error_pwd_index (249)
#define str_error_pwd_len (20)
#define str_error_pwd_pixLen (109)
#define str_error_pwd_centerX (9)
#define str_error_not_enough_mem_index (270)
#define str_error_not_enough_mem_len (20)
#define str_error_not_enough_mem_pixLen (111)
#define str_error_not_enough_mem_centerX (8)
#define str_error_cannot_add_index (291)
#define str_error_cannot_add_len (16)
#define str_error_cannot_add_pixLen (86)
#define str_error_cannot_add_centerX (21)
#define str_error_no_password_index (308)
#define str_error_no_password_len (19)
#define str_error_no_password_pixLen (102)
#define str_error_no_password_centerX (13)
#define str_option_pwd_index (328)
#define str_option_pwd_len (16)
#define str_option_pwd_pixLen (78)
#define str_option_pwd_centerX (25)
#define str_option_sort_index (345)
#define str_option_sort_len (7)
#define str_option_sort_pixLen (28)
#define str_option_sort_centerX (50)
#define str_option_param_index (353)
#define str_option_param_len (14)
#define str_option_param_pixLen (72)
#define str_option_param_centerX (28)
#define str_option_add_index (368)
#define str_option_add_len (20)
#define str_option_add_pixLen (111)
#define str_option_add_centerX (8)
#define str_option_change_pwd_index (389)
#define str_option_change_pwd_len (20)
#define str_option_change_pwd_pixLen (111)
#define str_option_change_pwd_centerX (8)
#define str_option_change_usr_index (410)
#define str_option_change_usr_len (19)
#define str_option_change_usr_pixLen (105)
#define str_option_change_usr_centerX (11)
#define str_option_change_name_index (430)
#define str_option_change_name_len (11)
#define str_option_change_name_pixLen (63)
#define str_option_change_name_centerX (32)
#define str_option_regen_index (442)
#define str_option_regen_len (9)
#define str_option_regen_pixLen (54)
#define str_option_regen_centerX (37)
#define str_option_delete_index (452)
#define str_option_delete_len (9)
#define str_option_delete_pixLen (52)
#define str_option_delete_centerX (38)
#define str_option_sort_no_index (462)
#define str_option_sort_no_len (10)
#define str_option_sort_no_pixLen (52)
#define str_option_sort_no_centerX (38)
#define str_option_sort_use_index (473)
#define str_option_sort_use_len (15)
#define str_option_sort_use_pixLen (79)
#define str_option_sort_use_centerX (24)
#define str_option_sort_alpha_index (489)
#define str_option_sort_alpha_len (7)
#define str_option_sort_alpha_pixLen (39)
#define str_option_sort_alpha_centerX (44)
#define str_option_key_index (497)
#define str_option_key_len (15)
#define str_option_key_pixLen (71)
#define str_option_key_centerX (28)
#define str_option_change_key_index (513)
#define str_option_change_key_len (19)
#define str_option_change_key_pixLen (104)
#define str_option_change_key_centerX (12)
#define str_option_show_key_index (533)
#define str_option_show_key_len (20)
#define str_option_show_key_pixLen (108)
#define str_option_show_key_centerX (10)
#define str_option_force_card_index (554)
#define str_option_force_card_len (19)
#define str_option_force_card_pixLen (99)
#define str_option_force_card_centerX (14)
#define str_option_force_enter_index (574)
#define str_option_force_enter_len (18)
#define str_option_force_enter_pixLen (91)
#define str_option_force_enter_centerX (18)
#define str_option_orientation_index (593)
#define str_option_orientation_len (21)
#define str_option_orientation_pixLen (115)
#define str_option_orientation_centerX (6)
#define str_option_keyboard_layout_index (615)
#define str_option_keyboard_layout_len (22)
#define str_option_keyboard_layout_pixLen (120)
#define str_option_keyboard_layout_centerX (4)
#define str_option_self_test_index (638)
#define str_option_self_test_len (10)
#define str_option_self_test_pixLen (56)
#define str_option_self_test_centerX (36)
#define str_option_full_reset_index (649)
#define str_option_full_reset_len (8)
#define str_option_full_reset_pixLen (48)
#define str_option_full_reset_centerX (40)
#define str_option_send_pwd_index (658)
#define str_option_send_pwd_len (20)
#define str_option_send_pwd_pixLen (111)
#define str_option_send_pwd_centerX (8)
#define str_option_send_usr_index (679)
#define str_option_send_usr_len (19)
#define str_option_send_usr_pixLen (97)
#define str_option_send_usr_centerX (15)
#define str_option_send_both_index (699)
#define str_option_send_both_len (16)
#define str_option_send_both_pixLen (88)
#define str_option_send_both_centerX (20)
#define str_order_approach_index (716)
#define str_order_approach_len (21)
#define str_order_approach_pixLen (120)
#define str_order_approach_centerX (4)
#define str_order_type_pwd_name_index (738)
#define str_order_type_pwd_name_len (20)
#define str_order_type_pwd_name_pixLen (106)
#define str_order_type_pwd_name_centerX (11)
#define str_order_type_pwd_data_index (759)
#define str_order_type_pwd_data_len (22)
#define str_order_type_pwd_data_pixLen (118)
#define str_order_type_pwd_data_centerX (5)
#define str_order_type_usr_name_index (782)
#define str_order_type_usr_name_len (24)
#define str_order_type_usr_name_pixLen (128)
#define str_order_type_usr_name_centerX (0)
#define str_recovery_eraseMem_index (807)
#define str_recovery_eraseMem_len (17)
#define str_recovery_eraseMem_pixLen (97)
#define str_recovery_eraseMem_centerX (15)
#define str_recovery_title_index (825)
#define str_recovery_title_len (20)
#define str_recovery_title_pixLen (114)
#define str_recovery_title_centerX (7)
#define str_recovery_full_index (846)
#define str_recovery_full_len (17)
#define str_recovery_full_pixLen (99)
#define str_recovery_full_centerX (14)
#define str_recovery_key_index (864)
#define str_recovery_key_len (14)
#define str_recovery_key_pixLen (78)
#define str_recovery_key_centerX (25)
#define str_reset_external_index (879)
#define str_reset_external_len (4)
#define str_reset_external_pixLen (21)
#define str_reset_external_centerX (53)
#define str_reset_brownout_index (884)
#define str_reset_brownout_len (4)
#define str_reset_brownout_pixLen (22)
#define str_reset_brownout_centerX (53)
#define str_reset_watchdog_index (889)
#define str_reset_watchdog_len (4)
#define str_reset_watchdog_pixLen (21)
#define str_reset_watchdog_centerX (53)
#define str_reset_jtag_index (894)
#define str_reset_jtag_len (4)
#define str_reset_jtag_pixLen (24)
#define str_reset_jtag_centerX (52)
#define str_reset_usb_index (899)
#define str_reset_usb_len (3)
#define str_reset_usb_pixLen (18)
#define str_reset_usb_centerX (55)
#define str_self_test_fram_fail_index (903)
#define str_self_test_fram_fail_len (19)
#define str_self_test_fram_fail_pixLen (109)
#define str_self_test_fram_fail_centerX (9)
#define str_self_test_rfid_fail_index (923)
#define str_self_test_rfid_fail_len (22)
#define str_self_test_rfid_fail_pixLen (122)
#define str_self_test_rfid_fail_centerX (3)
#define str_self_test_good_index (946)
#define str_self_test_good_len (20)
#define str_self_test_good_pixLen (107)
#define str_self_test_good_centerX (10)
#define str_self_test_fail_index (967)
#define str_self_test_fail_len (19)
#define str_self_test_fail_pixLen (107)
#define str_self_test_fail_centerX (10)
#define str_system_info_index (987)
#define str_system_info_len (12)
#define str_system_info_pixLen (69)
#define str_system_info_centerX (29)
#define str_system_ram_index (1000)
#define str_system_ram_len (5)
#define str_system_ram_pixLen (24)
#define str_system_ram_centerX (52)
#define str_system_pwd_index (1006)
#define str_system_pwd_len (5)
#define str_system_pwd_pixLen (24)
#define str_system_pwd_centerX (52)
#define str_system_volt_index (1012)
#define str_system_volt_len (9)
#define str_system_volt_pixLen (46)
#define str_system_volt_centerX (41)
#define str_system_entropy_index (1022)
#define str_system_entropy_len (10)
#define str_system_entropy_pixLen (52)
#define str_system_entropy_centerX (38)
#define str_system_version_index (1033)
#define str_system_version_len (11)
#define str_system_version_pixLen (56)
#define str_system_version_centerX (36)

static const uint8_t stringData[1045] PROGMEM =
{
'R', 'e', 'p', 'a', 'r', 'a', 't', 'i', 'o', 'n', ' ', 'd', 'e', 's', ' ', 'e', 
'r', 'r', 'e', 'u', 'r', 's', '\0', 'M', '.', 'a', '.', 'j', '.', ' ', 'd', 'e', 
' ', 'l', 'a', ' ', 'c', 'l', 'e', 'f', '\0', 'M', '.', 'a', '.', 'j', '.', ' ', 
'd', 'e', 's', ' ', 'm', 'o', 't', 's', ' ', 'd', 'e', ' ', 'p', 'a', 's', 's', 
'e', '\0', 'M', '.', 'a', '.', 'j', '.', ' ', 'd', 'e', ' ', 'l', 'a', ' ', 'v', 
'a', 'l', 'i', 'd', 'a', 't', 'i', 'o', 'n', '\0', 'M', '.', 'a', '.', 'j', '.', 
' ', 'd', 'e', ' ', 'l', 'a', ' ', 'c', 'a', 'r', 't', 'e', '\0', 'V', 'o', 'i', 
'c', 'i', ' ', 'v', 'o', 't', 'r', 'e', ' ', 'c', 'l', 'e', 'f', '\0', 'N', 'E', 
' ', 'P', 'A', 'S', ' ', 'D', 'E', 'B', 'R', 'A', 'N', 'C', 'H', 'E', 'R', '\0', 
'O', 'U', 'I', '\0', 'N', 'O', 'N', '\0', 'A', 'u', 't', 'o', 'r', 'i', 's', 'e', 
'r', ' ', 'c', 'o', 'm', '.', '\0', 'E', 'r', 'r', 'e', 'u', 'r', ' ', 'c', 'a', 
'r', 't', 'e', ' ', 'i', 'n', 'c', 'o', 'n', 'n', 'u', 'e', '\0', 'E', 'r', 'r', 
'e', 'u', 'r', ' ', 'a', 'u', 't', 'h', 'e', 'n', 't', 'i', 'f', 'i', 'c', 'a', 
't', 'i', 'o', 'n', '\0', 'E', 'r', 'r', 'e', 'u', 'r', ' ', 'd', 'e', ' ', 'l', 
'e', 'c', 't', 'u', 'r', 'e', '\0', 'E', 'r', 'r', 'e', 'u', 'r', ' ', 'd', '\'', 
'e', 'c', 'r', 'i', 't', 'u', 'r', 'e', '\0', 'M', 'a', 'u', 'v', 'a', 'i', 's', 
' ', 'm', 'o', 't', ' ', 'd', 'e', ' ', 'p', 'a', 's', 's', 'e', '\0', 'M', 'e', 
'm', 'o', 'i', 'r', 'e', ' ', 'i', 'n', 's', 'u', 'f', 'f', 'i', 's', 'a', 'n', 
't', 'e', '\0', 'A', 'j', 'o', 'u', 't', ' ', 'i', 'm', 'p', 'o', 's', 's', 'i', 
'b', 'l', 'e', '\0', 'P', 'a', 's', ' ', 'd', 'e', ' ', 'm', 'o', 't', ' ', 'd', 
'e', ' ', 'p', 'a', 's', 's', 'e', '\0', 'M', 'o', 't', ' ', 'd', 'e', ' ', 'p', 
'a', 's', 's', 'e', ' ', '.', '.', '.', '\0', 'T', 'r', 'i', ' ', '.', '.', '.', 
'\0', 'P', 'a', 'r', 'a', 'm', 'e', 't', 'r', 'e', 's', ' ', '.', '.', '.', '\0', 
'N', 'o', 'u', 'v', 'e', 'a', 'u', ' ', 'm', 'o', 't', ' ', 'd', 'e', ' ', 'p', 
'a', 's', 's', 'e', '\0', 'C', 'h', 'a', 'n', 'g', 'e', 'r', ' ', 'm', 'o', 't', 
' ', 'd', 'e', ' ', 'p', 'a', 's', 's', 'e', '\0', 'C', 'h', 'a', 'n', 'g', 'e', 
'r', ' ', 'i', 'd', 'e', 'n', 't', 'i', 'f', 'i', 'a', 'n', 't', '\0', 'C', 'h', 
'a', 'n', 'g', 'e', 'r', ' ', 'n', 'o', 'm', '\0', 'R', 'e', 'g', 'e', 'n', 'e', 
'r', 'e', 'r', '\0', 'S', 'u', 'p', 'p', 'r', 'i', 'm', 'e', 'r', '\0', 'P', 'a', 
's', ' ', 'd', 'e', ' ', 't', 'r', 'i', '\0', 'P', 'a', 'r', ' ', 'u', 't', 'i', 
'l', 'i', 's', 'a', 't', 'i', 'o', 'n', '\0', 'P', 'a', 'r', ' ', 'n', 'o', 'm', 
'\0', 'C', 'l', 'e', 'f', ' ', 'm', 'a', 'i', 't', 'r', 'e', ' ', '.', '.', '.', 
'\0', 'C', 'h', 'a', 'n', 'g', 'e', 'r', ' ', 'c', 'l', 'e', 'f', ' ', 'm', 'a', 
'i', 't', 'r', 'e', '\0', 'A', 'f', 'f', 'i', 'c', 'h', 'e', 'r', ' ', 'c', 'l', 
'e', 'f', ' ', 'm', 'a', 'i', 't', 'r', 'e', '\0', 'F', 'o', 'r', 'c', 'e', 'r', 
' ', 'u', 't', 'i', 'l', 'i', '.', ' ', 'c', 'a', 'r', 't', 'e', '\0', 'F', 'o', 
'r', 'c', 'e', 'r', ' ', 'u', 't', 'i', 'l', 'i', '.', ' ', 'c', 'l', 'e', 'f', 
'\0', 'R', 'e', 't', 'o', 'u', 'r', 'n', 'e', 'r', ' ', 'l', '\'', 'a', 'f', 'f', 
'i', 'c', 'h', 'a', 'g', 'e', '\0', 'C', 'h', 'a', 'n', 'g', 'e', 'r', ' ', 'l', 
'a', 'n', 'g', 'u', 'e', ' ', 'c', 'l', 'a', 'v', 'i', 'e', 'r', '\0', 'D', 'i', 
'a', 'g', 'n', 'o', 's', 't', 'i', 'c', '\0', 'F', 'O', 'R', 'M', 'A', 'T', 'E', 
'R', '\0', 'E', 'n', 'v', 'o', 'y', 'e', 'r', ' ', 'm', 'o', 't', ' ', 'd', 'e', 
' ', 'p', 'a', 's', 's', 'e', '\0', 'E', 'n', 'v', 'o', 'y', 'e', 'r', ' ', 'n', 
'o', 'm', ' ', 'd', '\'', 'u', 't', 'i', 'l', '.', '\0', 'E', 'n', 'v', 'o', 'y', 
'e', 'r', ' ', 'l', 'e', 's', ' ', 'd', 'e', 'u', 'x', '\0', 'A', 'p', 'p', 'r', 
'o', 'c', 'h', 'e', 'z', ' ', 'v', 'o', 't', 'r', 'e', ' ', 'c', 'a', 'r', 't', 
'e', '\0', 'E', 'n', 't', 'r', 'e', 'z', ' ', 'l', 'e', ' ', 'n', 'o', 'm', ' ', 
'd', 'u', ' ', 'm', 'd', 'p', '\0', 'E', 'n', 't', 'r', 'e', 'z', ' ', 'l', 'e', 
' ', 'm', 'o', 't', ' ', 'd', 'e', ' ', 'p', 'a', 's', 's', 'e', '\0', 'E', 'n', 
't', 'r', 'e', 'z', ' ', 'n', 'o', 'm', ' ', 'd', '\'', 'u', 't', 'i', 'l', 'i', 
's', 'a', 't', 'e', 'u', 'r', '\0', 'F', 'o', 'r', 'm', 'a', 't', 'a', 'g', 'e', 
' ', 'm', 'e', 'm', 'o', 'i', 'r', 'e', '\0', 'M', 'O', 'D', 'E', ' ', 'D', 'E', 
' ', 'R', 'E', 'C', 'U', 'P', 'E', 'R', 'A', 'T', 'I', 'O', 'N', '\0', 'F', 'O', 
'R', 'M', 'A', 'T', 'A', 'G', 'E', ' ', 'C', 'O', 'M', 'P', 'L', 'E', 'T', '\0', 
'E', 'N', 'T', 'R', 'E', 'R', ' ', 'L', 'A', ' ', 'C', 'L', 'E', 'F', '\0', 'E', 
'x', 't', '.', '\0', 'V', 'o', 'l', 't', '\0', 'W', 'd', 'r', '.', '\0', 'J', 'T', 
'A', 'G', '\0', 'U', 'S', 'B', '\0', 'M', 'e', 'm', 'o', 'i', 'r', 'e', ' ', 'd', 
'e', 'f', 'e', 'c', 't', 'u', 'e', 'u', 's', 'e', '\0', 'M', 'o', 'd', 'u', 'l', 
'e', ' ', 'r', 'f', 'i', 'd', ' ', 'd', 'e', 'f', 'e', 'c', 't', 'u', 'e', 'u', 
'x', '\0', 'A', 'p', 'p', 'a', 'r', 'e', 'i', 'l', ' ', 'e', 'n', ' ', 'b', 'o', 
'n', ' ', 'e', 't', 'a', 't', '\0', 'A', 'p', 'p', 'a', 'r', 'e', 'i', 'l', ' ', 
'd', 'e', 'f', 'e', 'c', 't', 'u', 'e', 'u', 'x', '\0', 'I', 'n', 'f', 'o', ' ', 
's', 'y', 's', 't', 'e', 'm', 'e', '\0', 'R', 'A', 'M', ' ', ':', '\0', 'M', 'D', 
'P', ' ', ':', '\0', 'T', 'e', 'n', 's', 'i', 'o', 'n', ' ', ':', '\0', 'E', 'n', 
't', 'r', 'o', 'p', 'i', 'e', ' ', ':', '\0', 'V', 'e', 'r', 's', 'i', 'o', 'n', 
' ', '1', '.', '0', '\0', };

#endif // STRING_HEADER_THOMAS_CHEVALIER
