#ifndef PINDEFINITION_HEADER_THOMAS_CHEVALIER
#define PINDEFINITION_HEADER_THOMAS_CHEVALIER

// SPI
#define SPI_SS_PIN_NUM 0
#define SPI_SCK_PIN_NUM 1
#define SPI_MOSI_PIN_NUM 2
#define SPI_MISO_PIN_NUM 3

#define SPI_SS_DDR DDRB
#define SPI_SCK_DDR DDRB
#define SPI_MOSI_DDR DDRB
#define SPI_MISO_DDR DDRB

// BUTTONS
#define BUTTON_1_PIN_CHANGE_NUM PCINT7
#define BUTTON_2_PIN_CHANGE_NUM PCINT5
#define BUTTON_3_PIN_CHANGE_NUM PCINT6
#define BUTTON_4_PIN_CHANGE_NUM PCINT4

#define BUTTON_1_PIN_NUM 7
#define BUTTON_2_PIN_NUM 5
#define BUTTON_3_PIN_NUM 6
#define BUTTON_4_PIN_NUM 4
 
#define BUTTON_1_DDR DDRB
#define BUTTON_2_DDR DDRB
#define BUTTON_3_DDR DDRB
#define BUTTON_4_DDR DDRB

#define BUTTON_1_PIN PINB
#define BUTTON_2_PIN PINB
#define BUTTON_3_PIN PINB
#define BUTTON_4_PIN PINB

#define BUTTON_1_PORT PORTB
#define BUTTON_2_PORT PORTB
#define BUTTON_3_PORT PORTB
#define BUTTON_4_PORT PORTB

// FRAM
#define FRAM_CS_DDR DDRF
#define FRAM_CS_PORT PORTF
#define FRAM_CS_PIN_NUM 7

// OLED
#define OLED_CS_DDR DDRF
#define OLED_CS_PORT PORTF
#define OLED_CS_PIN_NUM 0

#define OLED_DC_DDR DDRD
#define OLED_DC_PORT PORTD
#define OLED_DC_PIN_NUM 3

#define OLED_RES_DDR DDRD
#define OLED_RES_PORT PORTD
#define OLED_RES_PIN_NUM 2


// RFID
#define RFID_CS_DDR DDRD 
#define RFID_CS_PORT PORTD
#define RFID_CS_PIN_NUM 7

#define RFID_RES_DDR DDRC
#define RFID_RES_PORT PORTC
#define RFID_RES_PIN PINC
#define RFID_RES_PIN_NUM 6

// LED
#define LED_DDR DDRD
#define LED_PORT PORTD
#define LED_PIN_NUM 5


#endif // PINDEFINITION_HEADER_THOMAS_CHEVALIER
