#ifndef PINDEFINITION_HEADER_THOMAS_CHEVALIER
#define PINDEFINITION_HEADER_THOMAS_CHEVALIER

// BUTTONS
#define BUTTON_1_PIN_NUM 4
#define BUTTON_2_PIN_NUM 4
#define BUTTON_3_PIN_NUM 7

#define BUTTON_1_DDR DDRD
#define BUTTON_2_DDR DDRB
#define BUTTON_3_DDR DDRC

#define BUTTON_1_PIN PIND
#define BUTTON_2_PIN PINB
#define BUTTON_3_PIN PINC

#define BUTTON_1_PORT PORTD
#define BUTTON_2_PORT PORTB
#define BUTTON_3_PORT PORTC

// FRAM
#define FRAM_CS_DDR DDRF
#define FRAM_CS_PORT PORTF
#define FRAM_CS_PIN_NUM 7

// OLED
#define OLED_CS_DDR DDRD
#define OLED_CS_PORT PORTD
#define OLED_CS_PIN_NUM 0

#define OLED_DC_DDR DDRD
#define OLED_DC_PORT PORTD
#define OLED_DC_PIN_NUM 1

#define OLED_RES_DDR DDRD
#define OLED_RES_PORT PORTD
#define OLED_RES_PIN_NUM 2


// RFID
#define RFID_CS_DDR DDRD
#define RFID_CS_PORT PORTD
#define RFID_CS_PIN_NUM 6

#define RFID_RES_DDR DDRC
#define RFID_RES_PORT PORTC
#define RFID_RES_PIN_NUM 6


#endif // PINDEFINITION_HEADER_THOMAS_CHEVALIER